<?php

/**
 * @file
 */

/**
 * Define our variables (parameters) for each shortcode.
 */
function access_shortcodes_theme() {
  return [
    'shortcode_icon_block' => [
      'variables' => [
        'img' => '',
        'alt' => '',
        'title' => '',
        'text' => '',
        'link' => '',
        'boxed' => '',
        'btnlink' => '',
        'btntext' => '',
      ],
    ],
    'shortcode_cta_block' => [
      'variables' => [
        'heading' => '',
        'bg' => '',
        'img' => '',
        'alt' => '',
        'title' => '',
        'btnlink' => '',
        'btntext' => '',
      ],
    ],
    'shortcode_accordion' => [
      'variables' => [
        'summary' => '',
        'summarytag' => '',
        'text' => '',
        'color' => '',
      ],
    ],
    'shortcode_square' => [
      'variables' => [
        'icon' => '',
        'alt' => '',
        'title' => '',
        'text' => '',
        'link' => '',
        'color' => '',
        'flipText' => '',
        'flipBtnText' => '',
      ],
    ],
  ];
}
