access_misc.domain_logos:
  type: config_object
  label: 'Domain Logos and Descriptions Configuration'
  mapping:
    logos:
      type: sequence
      label: 'Domain Logo URLs'
      sequence:
        type: string
        label: 'Logo URL'
    descriptions:
      type: sequence
      label: 'Domain Descriptions'
      sequence:
        type: string
        label: 'Description'
