<?php

/**
 * @file
 * Contains hook implementations for the Ticketing module.
 */

/**
 * Implements hook_theme().
 *
 * @phpstan-return array<string, mixed>
 */
function ticketing_theme(): array {
  return [
    'ticketing_block' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_mail().
 *
 * @phpstan-param array<string, mixed> $message
 * @phpstan-param array<string, mixed> $params
 */
function ticketing_mail(string $key, array &$message, array $params): void {
  switch ($key) {
    case 'ticketing':
      // Send using submitter's email so the responder can be set in JSM.
      $from = $params['from'];
      $message['from'] = $from;
      $message['headers']['From'] = $from;
      $message['headers']['Sender'] = $from;
      $message['headers']['Return-Path'] = $from;

      $message['subject'] = $params['title'];
      $message['body'][] = $params['body'];

      // Add any cc's.
      if (array_key_exists('headers', $params) && array_key_exists('cc', $params['headers'])) {
        $message['headers']['cc'] = $params['headers']['cc'];
      }

      break;
  }
}
