<?php

/**
 * @file
 * Module updates.
 */

use Drupal\taxonomy\Entity\Term;

/**
 *
 */
function ccmnet_install() {
  \Drupal::state()->set('access_mentorship_interested', 0);
  // Add the tag 'Recruiting' to the 'State' Taxonomy.
  $states = [
    'Recruiting',
    'Reviewing',
    'In Progress',
    'In Progress and Recruiting',
    'Finishing Up',
    'Complete',
    'On Hold',
    'Halted',
  ];

  $weight = 0;

  foreach ($states as $state) {
    $term = Term::create([
      'name' => $state,
      'vid' => 'state',
      'weight' => $weight,
    ]);
    $term->save();
    $weight++;
  }
}

/**
 * Update to reset the access_mentorship_interested state.
 */
function ccmnet_update_10000() {
  \Drupal::state()->set('access_mentorship_interested', 0);

}

/**
 * Add state.
 */
function ccmnet_update_10002() {
  $term = Term::create([
    'name' => 'In Progress and Recruiting',
    'vid' => 'state',
    'weight' => 3,
  ]);
  $term->save();
}

/**
 * Add "Campus Champions AI Mentorship" term to the Mentorship Programs taxonomy.
 */
function ccmnet_update_10003() {
  // Load the vocabulary by its machine name.
  $vocabulary = 'mentorship_programs';

  // Check if the term already exists.
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
    'name' => 'Campus Champions AI Mentorship',
    'vid' => $vocabulary,
  ]);

  if (empty($terms)) {
    // Create the term if it doesn't exist.
    $term = Term::create([
      'vid' => $vocabulary,
      'name' => 'Campus Champions AI Mentorship',
    ]);
    $term->save();

    // Log the creation of the term.
    \Drupal::logger('ccmnet')->info('Added "Campus Champions AI Mentorship" term to the Mentorship Programs taxonomy.');
  }
  else {
    // Log that the term already exists.
    \Drupal::logger('ccmnet')->info('The "Campus Champions AI Mentorship" term already exists in the Mentorship Programs taxonomy.');
  }
}
