<?php

/**
 * @file
 * Hooks and preprocess functions for the ACCESS Outages module.
 */

/**
 * Implements hook_theme().
 *
 * @phpstan-return array<string, mixed>
 */
function access_outages_theme(): array {
  return [
    'outages_block' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for layout.
 *
 * Helps display affinity group outages by passing cider resource ids to the
 * access_outages library.
 *
 * @phpstan-param array<string, mixed> $vars
 */
function access_outages_preprocess_layout(array &$vars): void {
  $entity = $vars['content']['#entity'];
  if ($entity->bundle() == 'affinity_group') {
    $node_storage = \Drupal::entityTypeManager()->getStorage('node');
    $cider_resource_ids = [];
    if ($entity->hasField('field_cider_resources')) {
      $cider_ids = $entity->get('field_cider_resources')->getValue();
      foreach ($cider_ids as $cider_id) {
        $node = $node_storage->load($cider_id['target_id']);
        $cider_resource_ids[] = $node->get('field_access_global_resource_id')->value;
      }
    }
    if (count($cider_resource_ids) > 0) {
      $vars['#attached']['library'][] = 'access_outages/outages_library';
      $vars['#attached']['drupalSettings'] = ['ciderIds' => $cider_resource_ids];
    }
  }
}
