
<?php

/**
 * @file
 */

use Drupal\redirect\Entity\Redirect;

/**
 * Add redirects for retired pages.
 */
function access_cilink_update_10000() {
  Redirect::create([
    'redirect_source' => 'ci-links',
    'redirect_redirect' => 'internal:/knowledge-base/ci-links',
    'status_code' => 301,
  ])->save();
}

/**
 * Remove and replace redirects.
 */
function access_cilink_update_10001() {
  $ids = [];
  $ci = \Drupal::entityQuery('redirect')
    ->condition('redirect_redirect__uri', 'internal:/ci-links')
    ->accessCheck(FALSE)
    ->execute();
  $kbci = \Drupal::entityQuery('redirect')
    ->condition('redirect_redirect__uri', 'internal:/knowledge-base/ci-links')
    ->accessCheck(FALSE)
    ->execute();
  $ids = array_merge($ci, $kbci);
  $entities = Redirect::loadMultiple($ids);
  \Drupal::entityTypeManager()->getStorage('redirect')->delete($entities);

  Redirect::create([
    'redirect_source' => 'ci-links',
    'redirect_redirect' => 'internal:/knowledge-base/resources',
    'status_code' => 301,
  ])->save();
  Redirect::create([
    'redirect_source' => 'resources',
    'redirect_redirect' => 'internal:/knowledge-base/resources',
    'status_code' => 301,
  ])->save();
  Redirect::create([
    'redirect_source' => 'knowledge-base/ci-links',
    'redirect_redirect' => 'internal:/knowledge-base/resources',
    'status_code' => 301,
  ])->save();
}

/**
 * Remove OnDemand from webform_submission_data table.
 */
function access_cilink_update_10002() {
  // Get the database connection.
  $database = \Drupal::database();

  // Delete rows from the webform_submission_data table.
  $num_deleted = $database->delete('webform_submission_data')
    ->condition('webform_id', 'resource')
    ->condition('name', 'domain')
    ->condition('value', '901')
    ->execute();

  // Log the number of rows deleted.
  \Drupal::logger('access_cilink')->info('Deleted @count rows from webform_submission_data where webform_id = "resource", name = "domain", and value = "901".', [
    '@count' => $num_deleted,
  ]);

  // reindex the search api index
  $index = \Drupal::entityTypeManager()->getStorage('search_api_index')->load('ci_links');
  if ($index) {
    $index->indexItems();
    \Drupal::logger('access_cilink')->info('Reindexed the search API index "ci_links".');
  }
  else {
    \Drupal::logger('access_cilink')->error('Failed to load the search API index "ci_links".');
  }
}
