
<?php

/**
 * @file
 */

use Drupal\redirect\Entity\Redirect;

/**
 * Add redirects for retired pages.
 */
function access_cilink_update_10000() {
  Redirect::create([
    'redirect_source' => 'ci-links',
    'redirect_redirect' => 'internal:/knowledge-base/ci-links',
    'status_code' => 301,
  ])->save();
}

/**
 * Remove and replace redirects.
 */
function access_cilink_update_10001() {
  $ids = [];
  $ci = \Drupal::entityQuery('redirect')
    ->condition('redirect_redirect__uri', 'internal:/ci-links')
    ->accessCheck(FALSE)
    ->execute();
  $kbci = \Drupal::entityQuery('redirect')
    ->condition('redirect_redirect__uri', 'internal:/knowledge-base/ci-links')
    ->accessCheck(FALSE)
    ->execute();
  $ids = array_merge($ci, $kbci);
  $entities = Redirect::loadMultiple($ids);
  \Drupal::entityTypeManager()->getStorage('redirect')->delete($entities);

  Redirect::create([
    'redirect_source' => 'ci-links',
    'redirect_redirect' => 'internal:/knowledge-base/resources',
    'status_code' => 301,
  ])->save();
  Redirect::create([
    'redirect_source' => 'resources',
    'redirect_redirect' => 'internal:/knowledge-base/resources',
    'status_code' => 301,
  ])->save();
  Redirect::create([
    'redirect_source' => 'knowledge-base/ci-links',
    'redirect_redirect' => 'internal:/knowledge-base/resources',
    'status_code' => 301,
  ])->save();
}

/**
 * Remove OnDemand from webform_submission_data table.
 */
function access_cilink_update_10002() {
  // Get the database connection.
  $database = \Drupal::database();

  // Delete rows from the webform_submission_data table.
  $num_deleted = $database->delete('webform_submission_data')
    ->condition('webform_id', 'resource')
    ->condition('name', 'domain')
    ->condition('value', '901')
    ->execute();

  // Log the number of rows deleted.
  \Drupal::logger('access_cilink')->info('Deleted @count rows from webform_submission_data where webform_id = "resource", name = "domain", and value = "901".', [
    '@count' => $num_deleted,
  ]);

  // reindex the search api index
  $index = \Drupal::entityTypeManager()->getStorage('search_api_index')->load('ci_links');
  if ($index) {
    $index->indexItems();
    \Drupal::logger('access_cilink')->info('Reindexed the search API index "ci_links".');
  }
  else {
    \Drupal::logger('access_cilink')->error('Failed to load the search API index "ci_links".');
  }
}

/**
 * Delete old skill level in resource webform.
 */
function access_cilink_update_10003() {
  // Delete rows from the webform_submission_data table.
  \Drupal::database()->delete('webform_submission_data')
    ->condition('webform_id', 'resource')
    ->condition('name', 'skill_level')
    ->condition('value', '307')
    ->execute();
}

/**
 * Migrate description field data to new description_html field with basic_html format.
 */
function access_cilink_update_10004() {
  $query = \Drupal::database()->select('webform_submission_data', 'wsd');
  $query->fields('wsd', ['sid', 'value']);
  $query->condition('wsd.webform_id', 'resource');
  $query->condition('wsd.name', 'description');
  $resources = $query->execute()->fetchAll();

  foreach ($resources as $resource) {
    $insert = \Drupal::database()->insert('webform_submission_data')
      ->fields([
        'webform_id' => 'resource',
        'sid' => $resource->sid,
        'name' => 'description_html',
        'property' => 'value',
        'delta' => 0,
        'value' => $resource->value,
      ])
      ->execute();

    $insert = \Drupal::database()->insert('webform_submission_data')
      ->fields([
        'webform_id' => 'resource',
        'sid' => $resource->sid,
        'name' => 'description_html',
        'property' => 'format',
        'delta' => 0,
        'value' => 'basic_html',
      ])
      ->execute();
  }
}
